### ISSUE TITLE
Ghost writes to local file system

### ISSUE THREAD

**Issue by colinmeinke** [now-examples/ghost#1]
Hi, this is really interesting. I tried to get ghost set up on now a while back and gave up in the end. How did you get around ghost's writeable file system check (see https://github.com/TryGhost/Ghost/issues/7359)? My conclusion was that ghost currently isn't suitable to deploy with now, as even though you can configure it to write image uploads to s3, or the db to rds, it is still hard coded to write to local file for a few things (e.g. logs). More here https://gist.github.com/colinmeinke/978812f69bc9ea83390b231f8889318e

**Comment by evil-shrike** [comment]
Yeah, Ghost simple fails on start:

```
> now-examples-ghost@ start /home/nowuser/src
> node server.js
Unhandled rejection Error: insert into "settings" ("created_at", "created_by", "key", "type", "updated_at", "updated_by", "uuid", "value") values ('2017-01-31 23:07:40', 1, 'amp', 'blog', '2017-01-31 23:07:40', 1, 'b8ac6527-fa13-42a5-a575-99d875522c6d', 'true') - SQLITE_READONLY: attempt to write a readonly database
    at Error (native)
```

**Comment by justsee** [comment]
This Ghost example now fails on start as outlined above, but if the Ghost dependency in package.json is downgraded to `0.11.3` and deployed it starts successfully (though obviously can't be used to trial the admin console as the `content/data/ghost.db` is read-only).

**Comment by TooTallNate** [comment]
I'll tweak the README to suggest what I'm going to say here:

If you're going to stick with the default `sqlite3` backend (which is file-system based) then you should follow the typical Now-deployment paradigm. That is, start Ghost up locally in development mode, write a blog post and publish it so that the sqlite database is updated, and then you can create a new Now deployment and re-alias your URL. This paradigm requires a new deployment for any blog post changes or upgrading Ghost.

If you want to use a `mysql` or `postgres` database service, then you'll have to update the `config.js` file to point to an externally hosted database at this time. If you go this route then your Now deployment is more "live" such that you can edit and publish posts without creating a new Now deployment.

Let me know if that makes sense or if you have any more questions about those flows!
